/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgenceRouteImport } from './routes/agence'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as VendreRouteImport } from './routes/vendre'
import { Route as ActualitesIndexRouteImport } from './routes/actualites/index'
import { Route as ActualitesSlugRouteImport } from './routes/actualites/$slug'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminAutomatisationsRouteImport } from './routes/admin/automatisations'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminDesignRouteImport } from './routes/admin/design'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminMarketingRouteImport } from './routes/admin/marketing'
import { Route as AdminMatchingRouteImport } from './routes/admin/matching'
import { Route as AdminPortailClientRouteImport } from './routes/admin/portail-client'
import { Route as AdminProprietesRouteImport } from './routes/admin/proprietes'
import { Route as AdminRapportsRouteImport } from './routes/admin/rapports'
import { Route as AdminTachesRouteImport } from './routes/admin/taches'
import { Route as AdminTransactionsRouteImport } from './routes/admin/transactions'
import { Route as EquipeIndexRouteImport } from './routes/equipe/index'
import { Route as EquipeSlugRouteImport } from './routes/equipe/$slug'
import { Route as ProprietesIndexRouteImport } from './routes/proprietes/index'
import { Route as ProprietesSlugRouteImport } from './routes/proprietes/$slug'
import { Route as QuartiersIndexRouteImport } from './routes/quartiers/index'
import { Route as QuartiersSlugRouteImport } from './routes/quartiers/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenceRoute = AgenceRouteImport.update({
  id: '/agence',
  path: '/agence',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const VendreRoute = VendreRouteImport.update({
  id: '/vendre',
  path: '/vendre',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesIndexRoute = ActualitesIndexRouteImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesSlugRoute = ActualitesSlugRouteImport.update({
  id: '/actualites/$slug',
  path: '/actualites/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomatisationsRoute = AdminAutomatisationsRouteImport.update({
  id: '/automatisations',
  path: '/automatisations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchingRoute = AdminMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortailClientRoute = AdminPortailClientRouteImport.update({
  id: '/portail-client',
  path: '/portail-client',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProprietesRoute = AdminProprietesRouteImport.update({
  id: '/proprietes',
  path: '/proprietes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRapportsRoute = AdminRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTachesRoute = AdminTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const EquipeIndexRoute = EquipeIndexRouteImport.update({
  id: '/equipe/',
  path: '/equipe/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeSlugRoute = EquipeSlugRouteImport.update({
  id: '/equipe/$slug',
  path: '/equipe/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietesIndexRoute = ProprietesIndexRouteImport.update({
  id: '/proprietes/',
  path: '/proprietes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietesSlugRoute = ProprietesSlugRouteImport.update({
  id: '/proprietes/$slug',
  path: '/proprietes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartiersIndexRoute = QuartiersIndexRouteImport.update({
  id: '/quartiers/',
  path: '/quartiers/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuartiersSlugRoute = QuartiersSlugRouteImport.update({
  id: '/quartiers/$slug',
  path: '/quartiers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agence': typeof AgenceRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/vendre': typeof VendreRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/automatisations': typeof AdminAutomatisationsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/portail-client': typeof AdminPortailClientRoute
  '/admin/proprietes': typeof AdminProprietesRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/taches': typeof AdminTachesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/proprietes/': typeof ProprietesIndexRoute
  '/quartiers/': typeof QuartiersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agence': typeof AgenceRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/vendre': typeof VendreRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/automatisations': typeof AdminAutomatisationsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/portail-client': typeof AdminPortailClientRoute
  '/admin/proprietes': typeof AdminProprietesRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/taches': typeof AdminTachesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/equipe': typeof EquipeIndexRoute
  '/proprietes': typeof ProprietesIndexRoute
  '/quartiers': typeof QuartiersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agence': typeof AgenceRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/temoignages': typeof TemoignagesRoute
  '/vendre': typeof VendreRoute
  '/actualites/$slug': typeof ActualitesSlugRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/automatisations': typeof AdminAutomatisationsRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/matching': typeof AdminMatchingRoute
  '/admin/portail-client': typeof AdminPortailClientRoute
  '/admin/proprietes': typeof AdminProprietesRoute
  '/admin/rapports': typeof AdminRapportsRoute
  '/admin/taches': typeof AdminTachesRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/equipe/$slug': typeof EquipeSlugRoute
  '/proprietes/$slug': typeof ProprietesSlugRoute
  '/quartiers/$slug': typeof QuartiersSlugRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/equipe/': typeof EquipeIndexRoute
  '/proprietes/': typeof ProprietesIndexRoute
  '/quartiers/': typeof QuartiersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agence'
    | '/contact'
    | '/services'
    | '/temoignages'
    | '/vendre'
    | '/actualites/$slug'
    | '/admin/agenda'
    | '/admin/automatisations'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/design'
    | '/admin/documents'
    | '/admin/marketing'
    | '/admin/matching'
    | '/admin/portail-client'
    | '/admin/proprietes'
    | '/admin/rapports'
    | '/admin/taches'
    | '/admin/transactions'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/actualites/'
    | '/admin/'
    | '/equipe/'
    | '/proprietes/'
    | '/quartiers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agence'
    | '/contact'
    | '/services'
    | '/temoignages'
    | '/vendre'
    | '/actualites/$slug'
    | '/admin/agenda'
    | '/admin/automatisations'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/design'
    | '/admin/documents'
    | '/admin/marketing'
    | '/admin/matching'
    | '/admin/portail-client'
    | '/admin/proprietes'
    | '/admin/rapports'
    | '/admin/taches'
    | '/admin/transactions'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/actualites'
    | '/admin'
    | '/equipe'
    | '/proprietes'
    | '/quartiers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agence'
    | '/contact'
    | '/services'
    | '/temoignages'
    | '/vendre'
    | '/actualites/$slug'
    | '/admin/agenda'
    | '/admin/automatisations'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/design'
    | '/admin/documents'
    | '/admin/marketing'
    | '/admin/matching'
    | '/admin/portail-client'
    | '/admin/proprietes'
    | '/admin/rapports'
    | '/admin/taches'
    | '/admin/transactions'
    | '/equipe/$slug'
    | '/proprietes/$slug'
    | '/quartiers/$slug'
    | '/actualites/'
    | '/admin/'
    | '/equipe/'
    | '/proprietes/'
    | '/quartiers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgenceRoute: typeof AgenceRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VendreRoute: typeof VendreRoute
  ActualitesSlugRoute: typeof ActualitesSlugRoute
  EquipeSlugRoute: typeof EquipeSlugRoute
  ProprietesSlugRoute: typeof ProprietesSlugRoute
  QuartiersSlugRoute: typeof QuartiersSlugRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  EquipeIndexRoute: typeof EquipeIndexRoute
  ProprietesIndexRoute: typeof ProprietesIndexRoute
  QuartiersIndexRoute: typeof QuartiersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agence': {
      id: '/agence'
      path: '/agence'
      fullPath: '/agence'
      preLoaderRoute: typeof AgenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendre': {
      id: '/vendre'
      path: '/vendre'
      fullPath: '/vendre'
      preLoaderRoute: typeof VendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites/'
      preLoaderRoute: typeof ActualitesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites/$slug': {
      id: '/actualites/$slug'
      path: '/actualites/$slug'
      fullPath: '/actualites/$slug'
      preLoaderRoute: typeof ActualitesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automatisations': {
      id: '/admin/automatisations'
      path: '/automatisations'
      fullPath: '/admin/automatisations'
      preLoaderRoute: typeof AdminAutomatisationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design': {
      id: '/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matching': {
      id: '/admin/matching'
      path: '/matching'
      fullPath: '/admin/matching'
      preLoaderRoute: typeof AdminMatchingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portail-client': {
      id: '/admin/portail-client'
      path: '/portail-client'
      fullPath: '/admin/portail-client'
      preLoaderRoute: typeof AdminPortailClientRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proprietes': {
      id: '/admin/proprietes'
      path: '/proprietes'
      fullPath: '/admin/proprietes'
      preLoaderRoute: typeof AdminProprietesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapports': {
      id: '/admin/rapports'
      path: '/rapports'
      fullPath: '/admin/rapports'
      preLoaderRoute: typeof AdminRapportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taches': {
      id: '/admin/taches'
      path: '/taches'
      fullPath: '/admin/taches'
      preLoaderRoute: typeof AdminTachesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/equipe/': {
      id: '/equipe/'
      path: '/equipe'
      fullPath: '/equipe/'
      preLoaderRoute: typeof EquipeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe/$slug': {
      id: '/equipe/$slug'
      path: '/equipe/$slug'
      fullPath: '/equipe/$slug'
      preLoaderRoute: typeof EquipeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietes/': {
      id: '/proprietes/'
      path: '/proprietes'
      fullPath: '/proprietes/'
      preLoaderRoute: typeof ProprietesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietes/$slug': {
      id: '/proprietes/$slug'
      path: '/proprietes/$slug'
      fullPath: '/proprietes/$slug'
      preLoaderRoute: typeof ProprietesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quartiers/': {
      id: '/quartiers/'
      path: '/quartiers'
      fullPath: '/quartiers/'
      preLoaderRoute: typeof QuartiersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quartiers/$slug': {
      id: '/quartiers/$slug'
      path: '/quartiers/$slug'
      fullPath: '/quartiers/$slug'
      preLoaderRoute: typeof QuartiersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAutomatisationsRoute: typeof AdminAutomatisationsRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminDesignRoute: typeof AdminDesignRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMatchingRoute: typeof AdminMatchingRoute
  AdminPortailClientRoute: typeof AdminPortailClientRoute
  AdminProprietesRoute: typeof AdminProprietesRoute
  AdminRapportsRoute: typeof AdminRapportsRoute
  AdminTachesRoute: typeof AdminTachesRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAutomatisationsRoute: AdminAutomatisationsRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminDesignRoute: AdminDesignRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMatchingRoute: AdminMatchingRoute,
  AdminPortailClientRoute: AdminPortailClientRoute,
  AdminProprietesRoute: AdminProprietesRoute,
  AdminRapportsRoute: AdminRapportsRoute,
  AdminTachesRoute: AdminTachesRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgenceRoute: AgenceRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  TemoignagesRoute: TemoignagesRoute,
  VendreRoute: VendreRoute,
  ActualitesSlugRoute: ActualitesSlugRoute,
  EquipeSlugRoute: EquipeSlugRoute,
  ProprietesSlugRoute: ProprietesSlugRoute,
  QuartiersSlugRoute: QuartiersSlugRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  EquipeIndexRoute: EquipeIndexRoute,
  ProprietesIndexRoute: ProprietesIndexRoute,
  QuartiersIndexRoute: QuartiersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
